import AttentionItem from '../viewmodel/AttentionItem'
import Song from '../viewmodel/Song'

const attentions:AttentionItem[] = [
  new AttentionItem(0,'不负如来不负卿',$r('app.media.headImage1'),'25岁之前，能轻易的喜欢，但不能果断地放弃，30岁之后，能果断地放弃，却不能轻易地喜欢，不巧的是，我们卡在了25-30岁之间，既不能轻易地喜欢，也不能果断地放弃。',$r('app.media.comment1'),new Song($r('app.media.song_img1'),'漫步','许巍','543','4214'),'08:55'),
  new AttentionItem(1,'花香人自来',$r('app.media.headImage2'),'“有朝一日，会成为被喜欢的人觉得大吃一惊，被讨厌的人刮目相看的人。”',$r('app.media.comment2'),new Song($r('app.media.song_img2'),'告五人','给你一瓶魔法药水','423','4325'),'4月3号'),
  new AttentionItem(2,'Tender',$r('app.media.headImage3'),'那些离开你的人无论当初是出于什么原因离开的也许他犹豫过挣扎过不舍过但至少在他决定要走的那一瞬间他觉得没有你 他会过得更好',$r('app.media.comment3'),new Song($r('app.media.song_img3'),'Summer','CaIvin Harris','454','1231'),'三天前'),
  new AttentionItem(3,'无语君',$r('app.media.headImage4'),'喜欢就是喜欢哪里来的欲擒故纵、克制和隐忍我巴不得一日三餐吃了什么都告诉你路上遇见小猫舔爪子也要拍给你看',$r('app.media.comment4'),new Song($r('app.media.song_img4'),'自由像','林俊杰','798','455'),'15:12'),
  new AttentionItem(4,'寻光',$r('app.media.headImage5'),'如果马頔不认识舒傲寒，董小姐没牵过宋冬野的手，赵雷没有去过南方，尧十三错过了他北方的女王，祝星一开始就很爱陈粒，民谣还只是小众音乐你还是面不改色',$r('app.media.comment5'),new Song($r('app.media.song_img5'),'算了','万妮达','456','7866'),'22:45'),
  new AttentionItem(5,'睡觉睡觉',$r('app.media.headImage6'),'我已经过了餐桌上有只鸡就一定能吃到鸡腿的年纪了',$r('app.media.comment6'),new Song($r('app.media.song_img6'),'苦茶子','邵帅','464','1132'),'2月19号'),
  new AttentionItem(6,'煞风景',$r('app.media.headImage7'),'我上了那么多年学，熬了那么多夜，做那么多习题，顶着各种各样的压力，参加各种残酷的考试，谈恋爱，分手，工作，加班。我这么辛苦，竟然是为了成为一个普通人......',$r('app.media.comment7'),new Song($r('app.media.song_img7'),'迷途羔羊','张震岳','43','424'),'1月12号'),
  new AttentionItem(7,'是否是',$r('app.media.headImage8'),'月老与孟婆真是一对欢喜的冤家，一个许人来生，一个忘人前世。',$r('app.media.comment8'),new Song($r('app.media.song_img8'),'单车','陈奕迅','543','9999'),'三天前'),

]
export {attentions}