export default class Constants {
  static readonly FULL_WIDTH: string = '100%'
  static readonly FULL_HEIGHT: string = '100%'
  static readonly SIZE_160: number = 160
  static readonly SIZE_230: number = 230
  static readonly SIZE_50: number = 50
  static readonly SIZE_5: number = 5
  static readonly SIZE_80: number = 80
  static readonly SIZE_20: number = 20
  static readonly SIZE_90: number = 90
  static readonly SIZE_100: number = 100
  static readonly SIZE_30: number = 30
  static readonly SIZE_150: number = 150
  static readonly SIZE_200: number = 200
  static readonly SIZE_40: number = 40
  static readonly SIZE_110: number = 110
  static readonly SIZE_15: number = 15
  static readonly SIZE_25: number = 25
  static readonly SIZE_220: number = 220
  static readonly SIZE_2: number = 2
  static readonly SIZE_300: number = 300
}

export enum FS {
  FS_12 = 12,
  FS_14 = 14,
  FS_16 = 16,
  FS_20 = 20,
  FS_24 = 24,
  FS_13 = 13
}

export enum FW {
  FW_400 = 400,
  FW_600 = 600,
  FW_800 = 800
}

export enum SPACE {
  SPACE_5 = 5,
  SPACE_8 = 8,
  SPACE_10 = 10,
  SPACE_15 = 15,
  SPACE_20 = 20,
  SPACE_25 = 25,
  SPACE_40 = 40
}
